### ISSUE TITLE
In kindle format text isn't black

### ISSUE THREAD

**Issue by LGLO** [Dierk/FregeGoodness#2]
On kindle none part of text is totally black. It's dark grey. That makes reading not as comfortable as it could be.

**Comment by Dierk** [comment]
as reported on gitter: "Linux insides" and "Scala by example" and both are pale on kindle.

So it seems to a systematic deficiency in the gitbook processing.

**Comment by Dierk** [comment]
I contacted the gitbook support for this issue.

**Comment by AaronO** [comment]
@Dierk This was fixed by a PR we merged into `master` just a few hours ago: https://github.com/GitbookIO/gitbook/pull/904

This should be live in the coming days.

**Comment by Dierk** [comment]
Thanks! Closing the issue.
