### ISSUE TITLE
Wrong function composition in "Designing with functions and composition"

### ISSUE THREAD

**Issue by atennert** [Dierk/FregeGoodness#22]
The chapter contains two function compositions, which use the static function, that is also declared in this chapter.

The static function: `static :: Board -> Double`

The two usages:
`valueTree = static . prunedTree`
`maxValue = maximize . static . prune 5 . gameTree`

The usages are wrong, since static requires a Board (not a Tree of Board) and it returns a Double when maximize requires also a Tree.

The composition is correct in the linked example from the book ([example](https://github.com/Dierk/fregePluginApp/blob/game_only/src/frege/fregepluginapp/Minimax.fr)):
```
evaluateBy :: Ord a => (Board -> a) -> Int -> Board -> a
evaluateBy f lookahead = minimize . fmap f . prune lookahead . gameTree

nowValue :: Int -> Board -> (Double, Board)
nowValue lookahead board = (evaluateBy static lookahead board, board)
```

Here static is used with fmap, which applies it on the values in the Tree of Board.

So the fixed chapter would contain:
`valueTree = fmap static . prunedTree`
`maxValue = maximize . fmap static . prune 5 . gameTree`
but probably also needs some explanation on fmap, when putting it there.

**Comment by Dierk** [comment]
Thanks for the finding!
I have to look up whether there was an error when transferring the code from the implementation to the gitbook. 
Stay tuned.

**Comment by Dierk** [comment]
Solved with commit 49a8663ca91b2c9ec91df1e8aebeb7d30847f704.
Please verify and close the issue if you agree with the fix.

**Comment by atennert** [comment]
Thumbs up for the quick fix. The change is fine. I kept on reading and found the the same issue also on the next chapter until

> Generalizing static into fmap static

Can you include a fix for that too in the commit? I haven't seen any other issues in the rest of the book. 

Thank's for writing the book.

edit:
If you want to make a separate commit for the other chapter, just say so and I'll verify the above commit.

**Comment by Dierk** [comment]
Yes, I've recognized the same when proofreading and fixed it along the way.
BTW: it seems I had an earlier version where "static" worked on an array of Boards. When improving the implementation I failed to update the chapter accordingly.

Thanks for reading!

**Comment by atennert** [comment]
Looking good
