### ISSUE TITLE
"class Millimeter (Integral a) => a" needs to be "class (Integral a) => Millimeter a"

### ISSUE THREAD

**Issue by 0dB** [Dierk/FregeGoodness#3]
Error in code titled "The definition of a Millimeter type class for an integral type "a"" in section "A mini DSL with type classes/Initial Implementation".

**Comment by Dierk** [comment]
Thanks!
This used to be a difference to Haskell in the old compiler. Needs update. I wanted to wait, though, until the new compiler is fully finished.

**Comment by 0dB** [comment]
Ok. (Goes for all class declarations in the sample code.)
