### ISSUE TITLE
```instance Time Int``` needs to be added in "Step 2: Adding Durations"

### ISSUE THREAD

**Issue by 0dB** [Dierk/FregeGoodness#5]
E. g.

```
instance Time Int where
    sec x     = SEC x
    minutes x = x.sec * 60
    h       x = x.sec * 3600
```

In "Enhancing the DSL for type safety", code sample "The full solution for durations in one go". Else `3.sec + 1.h - 30.minutes == 1803.sec` won’t work.

**Comment by Dierk** [comment]
Yep. 
Thanks for working through the code so thoroughly and sharing your findings!

**Comment by 0dB** [comment]
Best way to learn: _Recreate_ code you see and get it to work (instead of copy&paste or downloading). That way I tripped over my own feet a few times — and discovered the issues I reported 😊

Good stuff in your book. Dot notation comes across well, for example. Also helped my understanding of class types. (I come from Clojure.)
