### ISSUE TITLE
Wrong example in "Fun with Numbers"

### ISSUE THREAD

**Issue by TGutowski** [Dierk/FregeGoodness#6]
https://dierk.gitbooks.io/fregegoodness/content/src/docs/asciidoc/what.html

Instead of 
1 / (1 - 1/3 + 2/3) -- Infinity
it should be
1 / (1 - 1/3 - 2/3) -- Infinity

**Comment by Dierk** [comment]
True!
Thanks for spotting!

**Comment by Dierk** [comment]
it appears that the value isn't even infinity any more but 9.007199254740992E15 as
`1-1/3 is 0.6666666666666667`
and
`2/3 is 0.6666666666666666`
.

Hm...

**Comment by y-taka-23** [comment]
Actually we can eval `1 / (1 - 1/6 - 5/6)` to `Infinity`, but I'm afraid that it results from not a feature of `Double` in Frege, but the spec of IEEE 754 floating-point arithmetic.

**Comment by Ingo60** [comment]
Correct @y-taka-23 
Since Frege Doubles follow the same rules as Java doubles do. Which is IEEE 754.
